# Generated by Django 4.2.26 on 2025-11-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('doc', 'Document'), ('kb', 'KBEntry')], max_length=3)),
                ('source_id', models.IntegerField()),
                ('ord', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='docs/')),
                ('mime', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('version', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='KBEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body_md', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('version', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('mode', models.CharField(choices=[('prepend', 'Prepend'), ('append', 'Append'), ('override', 'Override')], default='prepend', max_length=8)),
                ('scope', models.CharField(default='global', max_length=100)),
                ('priority', models.IntegerField(default=50)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.RunSQL(
            """
            ALTER TABLE knowledge_chunk
              ADD COLUMN IF NOT EXISTS embedding vector(1536);
            CREATE INDEX IF NOT EXISTS idx_chunk_embedding
              ON knowledge_chunk
              USING ivfflat (embedding vector_l2_ops)
              WITH (lists = 100);
            """,
            reverse_sql="""
            ALTER TABLE knowledge_chunk DROP COLUMN IF EXISTS embedding;
            DROP INDEX IF EXISTS idx_chunk_embedding;
            """
        )
    ]
