# Generated by Django 4.2.26 on 2025-11-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempnotice',
            name='severity',
            field=models.CharField(choices=[('info', 'Hinweis'), ('warning', 'Warnung'), ('critical', 'Störung'), ('maintenance', 'Wartung')], default='info', help_text='Bestimmt Farbe & Wichtigkeit im Chat (Info/Warning/Critical).', max_length=12),
        ),
    ]
