# Generated by Django 4.2.26 on 2025-11-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_tempnotice_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Hinweis'), ('warning', 'Warnung'), ('critical', 'Störung'), ('maintenance', 'Wartung')], default='info', max_length=18)),
                ('default_mode', models.CharField(choices=[('prepend', 'Prepend'), ('append', 'Append'), ('override', 'Override')], default='prepend', max_length=8)),
                ('default_scope', models.CharField(default='global', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('manual', 'Handbuch / Anleitung'), ('policy', 'Richtlinie / Policy'), ('faq', 'FAQ / Häufige Fragen'), ('other', 'Sonstiges')], default='other', max_length=20),
        ),
    ]
