# Generated by Django 4.2.26 on 2025-11-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_maintenancetemplate_document_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='document',
            name='version',
        ),
        migrations.AddField(
            model_name='document',
            name='index_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='index_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='indexed_chunks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Hochgeladen'), ('extracting', 'Extrahiere'), ('indexing', 'Indexiere'), ('indexed', 'Fertig'), ('error', 'Fehler')], default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancetemplate',
            name='severity',
            field=models.CharField(choices=[('info', 'Hinweis'), ('warning', 'Warnung'), ('critical', 'Störung'), ('maintenance', 'Wartung')], default='info', max_length=16),
        ),
    ]
