# Generated by Django 4.2.26 on 2026-01-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_remove_document_hash_remove_document_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='source_kind',
            field=models.CharField(choices=[('doc', 'Document'), ('kb', 'KBEntry'), ('pdf', 'PDF')], max_length=8),
        ),
    ]
