# Generated by Django 4.2.26 on 2026-01-30 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0006_alter_chunk_source_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('representative_question', models.TextField()),
                ('representative_question_norm', models.TextField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('priority', models.IntegerField(default=50)),
                ('count', models.IntegerField(default=1)),
                ('reason_top', models.CharField(choices=[('low_retrieval', 'Low retrieval confidence'), ('non_answer', 'Model non-answer'), ('keyword', 'Keyword escalation'), ('citations_missing', 'Citations missing'), ('other', 'Other')], default='other', max_length=32)),
                ('linked_kb_entry_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gaps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeGapEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_raw', models.TextField()),
                ('question_redacted', models.TextField()),
                ('reason', models.CharField(choices=[('low_retrieval', 'Low retrieval confidence'), ('non_answer', 'Model non-answer'), ('keyword', 'Keyword escalation'), ('citations_missing', 'Citations missing'), ('other', 'Other')], default='other', max_length=32)),
                ('best_score', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('top_sources', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('session_id', models.IntegerField(blank=True, null=True)),
                ('ticket_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='knowledge.knowledgegap')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['reason', '-created_at'], name='knowledge_k_reason_b577aa_idx'), models.Index(fields=['ticket_id'], name='knowledge_k_ticket__7f8971_idx'), models.Index(fields=['session_id'], name='knowledge_k_session_9b23ae_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgegap',
            index=models.Index(fields=['status', '-count'], name='knowledge_k_status_713912_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgegap',
            index=models.Index(fields=['-last_seen_at'], name='knowledge_k_last_se_291121_idx'),
        ),
    ]
