# Generated by Django 4.2.26 on 2025-11-24 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_companyprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='tagline',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Company Description'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='company_icons/', verbose_name='Company Icon'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Support Email'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='support_phone',
            field=models.CharField(blank=True, max_length=64, verbose_name='Support Phone'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(default='Your Company', max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyprofile_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(default='Support Bot', max_length=100)),
                ('bot_role', models.CharField(default='Customer Support Assistant', max_length=200)),
                ('system_prompt', models.TextField(default='You are a helpful customer support assistant. Be professional, empathetic, and provide accurate information based on the knowledge base.', help_text="Base prompt that defines the bot's behavior.")),
                ('greeting_message', models.TextField(default="Hello! I'm your support assistant. How can I help you today?")),
                ('conversation_tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('casual', 'Casual')], default='professional', max_length=32)),
                ('response_length', models.CharField(choices=[('short', 'Short'), ('moderate', 'Moderate'), ('detailed', 'Detailed')], default='moderate', max_length=32)),
                ('creativity_level', models.FloatField(default=0.3, help_text='Temperature between 0.0 (focused) and 1.0 (creative).')),
                ('confidence_threshold', models.IntegerField(default=75, help_text='Percent. Below this, conversation may be escalated.')),
                ('auto_escalation_enabled', models.BooleanField(default=True)),
                ('escalation_keywords', models.TextField(blank=True, help_text='Comma-separated keywords that should trigger escalation (e.g. urgent,critical,refund).')),
                ('proactive_help_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbotconfig_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
