# Generated by Django 4.2.26 on 2025-11-24 14:11

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_companyprofile_tagline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconfig',
            name='openai_api_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='API-Key für ChatGPT (wird verschlüsselt gespeichert).', max_length=200)),
        ),
    ]
