# Generated by Django 4.2.26 on 2025-11-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_chatbotconfig_openai_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_level',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('pro', 'Pro')], default='free', max_length=20),
        ),
    ]
