# Generated by Django 4.2.26 on 2025-11-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('expected_hint', models.TextField(blank=True)),
                ('last_accuracy', models.BooleanField(null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
