# Generated by Django 4.2.26 on 2026-01-09 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Iteration', max_length=120)),
                ('status', models.CharField(choices=[('running', 'running'), ('done', 'done'), ('failed', 'failed')], default='running', max_length=10)),
                ('retrieval_top_k', models.IntegerField(default=6)),
                ('semantic_threshold', models.FloatField(default=0.8)),
                ('prompt_version', models.CharField(default='v1', max_length=50)),
                ('total', models.IntegerField(default=0)),
                ('evaluated', models.IntegerField(default=0)),
                ('accuracy_auto', models.FloatField(blank=True, null=True)),
                ('citation_compliance', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, default='')),
                ('sources', models.JSONField(blank=True, default=list)),
                ('status_ok', models.BooleanField(default=False)),
                ('sources_ok', models.BooleanField(default=False)),
                ('has_citation_markers', models.BooleanField(default=False)),
                ('semantic_ok', models.BooleanField(default=False)),
                ('semantic_similarity', models.FloatField(blank=True, null=True)),
                ('human_correctness', models.IntegerField(blank=True, null=True)),
                ('human_completeness', models.IntegerField(blank=True, null=True)),
                ('human_citations', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.evalitem')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quality.evalrun')),
            ],
            options={
                'unique_together': {('run', 'item')},
            },
        ),
    ]
