# Generated by Django 4.2.26 on 2026-01-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_evalrun_evalresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalresult',
            name='auto_correct',
            field=models.BooleanField(default=False),
        ),
    ]
