# Generated by Django 4.2.26 on 2026-01-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_evalresult_auto_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalitem',
            name='last_f1_like',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalitem',
            name='last_precision_like',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalitem',
            name='last_recall_like',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalitem',
            name='last_similarity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
