# Generated by Django 4.2.26 on 2026-01-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_evalitem_last_f1_like_evalitem_last_precision_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalresult',
            name='semantic_f1_like',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='semantic_precision_like',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='semantic_recall_like',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
