# Generated by Django 4.2.26 on 2026-01-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_evalresult_semantic_f1_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalrun',
            name='semantic_method',
            field=models.CharField(choices=[('v1', 'V1 (Coverage)'), ('v2', 'V2 (Hybrid: Coverage + Global)'), ('legacy', 'Legacy (Global Cosine)')], default='v1', max_length=20),
        ),
    ]
