# Generated by Django 4.2.26 on 2026-01-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_evalrun_semantic_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalresult',
            name='has_citation_markers',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
