# Generated by Django 4.2.26 on 2026-02-05 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quality', '0007_alter_evalresult_has_citation_markers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evalresult',
            old_name='human_citations',
            new_name='transparency_score',
        ),
        migrations.RemoveField(
            model_name='evalresult',
            name='human_completeness',
        ),
        migrations.RemoveField(
            model_name='evalresult',
            name='human_correctness',
        ),
        migrations.AddField(
            model_name='evalitem',
            name='category',
            field=models.CharField(choices=[('concept', 'Begriffe/Rollen/Grundlagen'), ('architecture', 'Architektur/Komponenten'), ('process', 'Prozesse/Fachlogik'), ('support', 'Fehler/Supportfall'), ('governance', 'Governance/Transfer')], default='concept', max_length=20),
        ),
        migrations.AddField(
            model_name='evalitem',
            name='expected_sources_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='evalitem',
            name='kb_expected',
            field=models.CharField(choices=[('yes', 'Wissensbasis vorhanden'), ('partial', 'teilweise vorhanden'), ('no', 'Wissensbasis fehlt (Wissenslücke)')], default='yes', max_length=10),
        ),
        migrations.AddField(
            model_name='evalitem',
            name='should_escalate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evalitem',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='closed_loop_status',
            field=models.CharField(choices=[('none', 'keine Wissenslücke erkannt'), ('detected', 'Wissenslücke erkannt'), ('ticketed', 'Ticket/Task angelegt'), ('kb_written', 'KB-Artikel erstellt/erweitert'), ('reintegrated', 'Retrieval aktualisiert (re-integriert)')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='escalation_reason',
            field=models.CharField(blank=True, choices=[('no_kb', 'fehlende Wissensbasis'), ('low_confidence', 'geringe Antwortsicherheit/Qualität'), ('policy', 'Policy/Compliance'), ('missing_context', 'fehlende Kontextinformationen'), ('system_error', 'System-/Schnittstellenfehler'), ('other', 'Sonstiges')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='handover_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='handover_context_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='kb_article_ref',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='knowledge_gap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='citations_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='dataset_name',
            field=models.CharField(blank=True, default='gematik', max_length=120),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='dataset_version',
            field=models.CharField(blank=True, default='v1', max_length=60),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='min_f1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='min_global',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='min_recall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='rag_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='HumanRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctness', models.IntegerField(blank=True, null=True)),
                ('completeness', models.IntegerField(blank=True, null=True)),
                ('citations', models.IntegerField(blank=True, null=True)),
                ('clarity', models.IntegerField(blank=True, null=True)),
                ('usefulness', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_ratings', to='quality.evalitem')),
                ('rater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_ratings', to='quality.evalrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'item'], name='quality_hum_run_id_0f4a50_idx'), models.Index(fields=['run', 'rater'], name='quality_hum_run_id_c4f87a_idx')],
                'unique_together': {('run', 'item', 'rater')},
            },
        ),
    ]
