# Generated by Django 4.2.26 on 2025-11-25 14:03

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('api_url', models.URLField(blank=True, help_text='Basis-URL des Ticket-Systems, z. B. https://api.freshdesk.com/v2/tickets')),
                ('api_key', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='API-Key für das Ticket-System (verschlüsselt gespeichert)', max_length=200))),
                ('api_format', models.CharField(default='json-default', help_text='Format des JSON-Bodies (für spätere Erweiterungen)', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='exported',
            field=models.BooleanField(default=False, help_text='Wurde dieses Ticket bereits an das externe Ticket-System übertragen?'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='exported_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt der letzten erfolgreichen Übertragung', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID des Tickets im externen System', max_length=100),
        ),
    ]
