# Generated by Django 4.2.26 on 2025-11-25 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsession_greeting_sent'),
        ('tickets', '0002_ticketsystemconfig_ticket_exported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='chat.chatsession'),
        ),
    ]
