# Generated by Django 4.2.26 on 2026-01-05 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customer_serviceplan_and_more'),
        ('tickets', '0003_ticket_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='users.customer'),
        ),
    ]
