# Generated by Django 4.2.26 on 2025-11-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('open', 'Offen'), ('done', 'Erledigt')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
