# Generated by Django 4.2.26 on 2025-11-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_status_chatsession_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='greeting_sent',
            field=models.BooleanField(default=False),
        ),
    ]
