# Generated by Django 4.2.26 on 2026-01-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsession_greeting_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='rating_text',
            field=models.TextField(blank=True),
        ),
    ]
