# Generated by Django 4.2.26 on 2025-11-25 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employee', 'Mitarbeiter'), ('admin', 'Administrator')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Company', max_length=255, verbose_name='Company Name')),
                ('description', models.TextField(blank=True, verbose_name='Company Description')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='company_icons/', verbose_name='Company Icon')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='Support Email')),
                ('support_phone', models.CharField(blank=True, max_length=64, verbose_name='Support Phone')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyprofile_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='API-Key für ChatGPT (wird verschlüsselt gespeichert).', max_length=200))),
                ('bot_name', models.CharField(default='Support Bot', max_length=100)),
                ('bot_role', models.CharField(default='Customer Support Assistant', max_length=200)),
                ('system_prompt', models.TextField(default='You are a helpful customer support assistant. Be professional, empathetic, and provide accurate information based on the knowledge base.', help_text="Base prompt that defines the bot's behavior.")),
                ('greeting_message', models.TextField(default="Hello! I'm your support assistant. How can I help you today?")),
                ('conversation_tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('casual', 'Casual')], default='professional', max_length=32)),
                ('response_length', models.CharField(choices=[('short', 'Short'), ('moderate', 'Moderate'), ('detailed', 'Detailed')], default='moderate', max_length=32)),
                ('creativity_level', models.FloatField(default=0.3, help_text='Temperature between 0.0 (focused) and 1.0 (creative).')),
                ('confidence_threshold', models.IntegerField(default=75, help_text='Percent. Below this, conversation may be escalated.')),
                ('auto_escalation_enabled', models.BooleanField(default=True)),
                ('escalation_keywords', models.TextField(blank=True, help_text='Comma-separated keywords that should trigger escalation (e.g. urgent,critical,refund).')),
                ('proactive_help_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbotconfig_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
