# Generated by Django 4.2.26 on 2026-02-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotconfig',
            name='system_prompt',
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='citations_default_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='rag_default_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='retrieval_top_k_default',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='semantic_method_default',
            field=models.CharField(choices=[('v1', 'V1 (Coverage)'), ('v2', 'V2 (Hybrid)'), ('legacy', 'Legacy')], default='v1', max_length=20),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='semantic_threshold_default',
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='system_prompt_norag',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='system_prompt_rag',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='user_template_norag',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='user_template_rag',
            field=models.TextField(blank=True, default=''),
        ),
    ]
